version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build: ./worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # S3_RESULT_BUCKET: taskflow-results   # optional, set to enable S3 upload
      # AWS_REGION: us-east-1
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: 2
